-- Created for "sitelen seli kiwen" font (https://www.kreativekorp.com/software/fonts/sitelenselikiwen/)

local l = require("latin_to_sitelen_pona")

return {
	[l.anpa] = {
		[l.lawa] = "󿤀",
	},
	[l.ijo] = {
		[l.akesi] = "󿤁",
		[l.ala] = "󿤂",
		[l.alasa] = "󿤃",
		[l.ale] = "󿤄",
		[l.ali] = "󿤄",
		[l.anpa] = "󿤅",
		[l.ante] = "󿤆",
		[l.anu] = "󿤇",
		[l.apeja] = "󿤈",
		[l.awen] = "󿤉",
		[l.en] = "󿤊",
		[l.esun] = "󿤋",
		[l.ilo] = "󿤍",
		[l.insa] = "󿤎",
		[l.jaki] = "󿤏",
		[l.jan] = "󿤐",
		[l.jelo] = "󿤑",
		[l.jo] = "󿤒",
		[l.kala] = "󿤓",
		[l.kalama] = "󿤔",
		[l.kama] = "󿤕",
		[l.kasi] = "󿤖",
		[l.ken] = "󿤗",
		[l.kepeken] = "󿤘",
		[l.kepen] = "󿤘",
		[l.kijetesantakalu] = "󿤙",
		[l.kili] = "󿤚",
		[l.kin] = "󿤛",
		[l.kipisi] = "󿤜",
		[l.kiwen] = "󿤝",
		[l.ko] = "󿤞",
		[l.kon] = "󿤟",
		[l.kule] = "󿤠",
		[l.kulupu] = "󿤡",
		[l.kute] = "󿤢",
		[l.lape] = "󿤣",
		[l.laso] = "󿤤",
		[l.lawa] = "󿤥",
		[l.leko] = "󿤦",
		[l.len] = "󿤧",
		[l.lete] = "󿤨",
		[l.lili] = "󿤩",
		[l.linja] = "󿤪",
		[l.lipu] = "󿤫",
		[l.loje] = "󿤬",
		[l.lon] = "󿤭",
		[l.luka] = "󿤮",
		[l.lukin] = "󿤯",
		[l.lupa] = "󿤰",
		[l.ma] = "󿤱",
		[l.mama] = "󿤲",
		[l.meli] = "󿤴",
		[l.mi] = "󿤵",
		[l.mije] = "󿤶",
		[l.moku] = "󿤷",
		[l.moli] = "󿤸",
		[l.monsi] = "󿤹",
		[l.monsuta] = "󿤺",
		[l.mu] = "󿤻",
		[l.mun] = "󿤼",
		[l.musi] = "󿤽",
		[l.mute] = "󿤾",
		[l.namako] = "󿤿",
		[l.nanpa] = "󿥀",
		[l.nasa] = "󿥁",
		[l.nasin] = "󿥂",
		[l.nena] = "󿥃",
		[l.ni] = "󿥄", -- TODO: add ijo-ni-li-seme
		[l.nimi] = "󿥅",
		[l.noka] = "󿥆",
		[l.oko] = "󿥇",
		[l.olin] = "󿥈",
		[l.ona] = "󿥉",
		[l.open] = "󿥊",
		[l.pakala] = "󿥋",
		[l.pake] = "󿥌",
		[l.pali] = "󿥍",
		[l.palisa] = "󿥎",
		[l.pan] = "󿥏",
		[l.pana] = "󿥐",
		[l.pilin] = "󿥑",
		[l.pimeja] = "󿥒",
		[l.pini] = "󿥓",
		[l.pipi] = "󿥔",
		[l.poka] = "󿥕",
		[l.poki] = "󿥖",
		[l.pona] = "󿥗",
		[l.pu] = "󿥘",
		[l.seli] = "󿥚",
		[l.selo] = "󿥛",
		[l.seme] = "󿥜",
		[l.sewi] = "󿥝",
		[l.sijelo] = "󿥞",
		[l.sike] = "󿥟",
		[l.sin] = "󿥠",
		[l.sina] = "󿥡",
		[l.sinpin] = "󿥢",
		[l.sitelen] = "󿥣",
		[l.sona] = "󿥤",
		[l.soweli] = "󿥥",
		[l.suli] = "󿥦",
		[l.suno] = "󿥧",
		[l.supa] = "󿥨",
		[l.suwi] = "󿥩",
		[l.tan] = "󿥪",
		[l.taso] = "󿥫",
		[l.tawa] = "󿥬",
		[l.telo] = "󿥭",
		[l.tenpo] = "󿥮",
		[l.toki] = "󿥯",
		[l.tomo] = "󿥰",
		[l.tonsi] = "󿥱",
		[l.tu] = "󿥲",
		[l.unpa] = "󿥳",
		[l.uta] = "󿥴",
		[l.utala] = "󿥵",
		[l.walo] = "󿥶",
		[l.wan] = "󿥷",
		[l.waso] = "󿥸",
		[l.wawa] = "󿥹",
		[l.weka] = "󿥺",
		[l.wile] = "󿥻",
	},
	[l.ike] = {
		[l.ala] = "󿥼",
		[l.lili] = "󿥽",
		[l.lukin] = "󿥾",
		[l.mute] = "󿴜",
	},
	[l.ilo] = {
		[l.kipisi] = "󿥿",
		[l.lape] = "󿦀",
		[l.lukin] = "󿦁",
		[l.moli] = "󿦂",
		[l.musi] = "󿦃",
		[l.nanpa] = "󿦄",
		[l.oko] = "󿦅",
		[l.open] = "󿦆",
		[l.suno] = "󿦇",
		[l.toki] = "󿦈",
	},
	[l.jan] = {
		[l.ala] = "󿦉",
		[l.alasa] = "󿦊",
		[l.ale] = "󿦋",
		[l.ali] = "󿦋",
		[l.ante] = "󿦌",
		[l.ike] = "󿦍",
		[l.kala] = "󿦎",
		[l.kalama] = "󿦏",
		[l.kasi] = "󿦐",
		[l.kulupu] = "󿦑",
		[l.lawa] = "󿦒",
		[l.lili] = "󿦓",
		[l.monsuta] = "󿦔",
		[l.mute] = "󿦕",
		[l.nasa] = "󿦖",
		[l.ni] = "󿴁",
		[l.olin] = "󿦗",
		[l.pakala] = "󿦘",
		[l.pali] = "󿦙",
		[l.poka] = "󿦚",
		[l.pona] = "󿦛",
		[l.sama] = "󿦜",
		[l.seme] = "󿦝",
		[l.sewi] = "󿦞",
		[l.sin] = "󿦟",
		[l.sona] = "󿦠",
		[l.suli] = "󿦡",
		[l.suwi] = "󿦢",
		[l.toki] = "󿦣",
		[l.unpa] = "󿦤",
		[l.utala] = "󿦥",
		[l.wawa] = "󿦦",
	},
	[l.kala] = {
		[l.lete] = "󿦧",
		[l.lili] = "󿦨",
	},
	[l.kalama] = {
		[l.musi] = "󿦩",
	},
	[l.kasi] = {
		[l.jelo] = "󿦪",
		[l.kule] = "󿦫",
		[l.laso] = "󿦬",
		[l.lili] = "󿦭",
		[l.loje] = "󿦮",
		[l.pimeja] = "󿦯",
		[l.walo] = "󿦰",
	},
	[l.kijetesantakalu] = {
		[l.soweli] = "󿴨",
	},
	[l.kili] = {
		[l.jelo] = "󿦱",
		[l.laso] = "󿦲",
		[l.lili] = "󿦳",
		[l.loje] = "󿦴",
		[l.palisa] = "󿦵",
		[l.pimeja] = "󿦶",
		[l.suwi] = "󿦷",
		[l.walo] = "󿦸",
	},
	[l.kiwen] = {
		[l.jelo] = "󿦹",
		[l.kasi] = "󿦺",
		[l.laso] = "󿦻",
		[l.lete] = "󿦼",
		[l.lili] = "󿦽",
		[l.loje] = "󿦾",
		[l.mun] = "󿦿",
		[l.pimeja] = "󿧀",
		[l.seli] = "󿧁",
		[l.suno] = "󿧂",
		[l.walo] = "󿧃",
	},
	[l.ko] = {
		[l.jaki] = "󿧄",
		[l.jelo] = "󿧅",
		[l.kasi] = "󿧆",
		[l.kule] = "󿧇",
		[l.laso] = "󿧈",
		[l.lete] = "󿧉",
		[l.lili] = "󿧊",
		[l.loje] = "󿧋",
		[l.nasa] = "󿧌",
		[l.pimeja] = "󿧍",
		[l.seli] = "󿧎",
		[l.walo] = "󿧏",
		[l.lete] = "󿧐",
	},
	[l.kule] = {
		[l.kasi] = "󿴣",
		[l.kili] = "󿴡",
		[l.ma] = "󿴟",
		[l.mun] = "󿴦",
		[l.pilin] = "󿴧",
		[l.sewi] = "󿴤",
		[l.suno] = "󿴢",
		[l.telo] = "󿴥",
		[l.uta] = "󿴠",
	},
	[l.laso] = {
		[l.kasi] = "󿮽",
		[l.mun] = "󿮾",
		[l.sewi] = "󿮿",
		[l.telo] = "󿯁",
	},
	[l.len] = {
		[l.jan] = "󿧑",
		[l.jelo] = "󿧒",
		[l.laso] = "󿧓",
		[l.lawa] = "󿧔",
		[l.lili] = "󿧕",
		[l.loje] = "󿧖",
		[l.luka] = "󿧗",
		[l.noka] = "󿧘",
		[l.pimeja] = "󿧙",
		[l.sin] = "󿧚",
		[l.walo] = "󿧛",
	},
	[l.linja] = {
		[l.lili] = "󿧜",
		[l.pona] = "󿧝",
		[l.sike] = "󿯴",
		[l.suwi] = "󿯵",
	},
	[l.lipu] = {
		[l.kasi] = "󿧞",
		[l.kule] = "󿴓",
		[l.majuna] = "󿴑",
		[l.nanpa] = "󿧟",
		[l.nimi] = "󿯂",
		[l.sewi] = "󿧠",
		[l.sona] = "󿧡",
		[l.tenpo] = "󿯄",
		[l.toki] = "󿧢",
		[l.unpa] = "󿴗",
	},
	[l.loje] = {
		[l.jelo] = "󿯅",
		[l.walo] = "󿯆",
	},
	[l.luka] = { -- TODO: improve
		[l.luka] = {
			[l.luka] = {
				[l.luka] = "󿵩",
				[l.tu] = {
					[l.wan] = "󿯊",
					[l.tu] = "󿯉",
				},
				[l.wan] = {
					[l.tu] = "󿯌",
				},
			},
			[l.tu] = {
				[l.tu] = "󿩎",
				[l.wan] = "󿩌",
			},
			[l.wan] = {
				[l.tu] = "󿩍",
			},
		},
		[l.tu] = {
			[l.tu] = "󿩈",
			[l.wan] = "󿩆",
		},
		[l.wan] = {
			[l.tu] = "󿩇",
		},
	},
	[l.lupa] = {
		[l.jaki] = "󿧤",
		[l.kiwen] = "󿧥",
		[l.kute] = "󿧦",
		[l.lili] = "󿧧",
		[l.meli] = "󿧨",
		[l.monsi] = "󿧩",
		[l.nena] = "󿧪",
		[l.tomo] = "󿧫",
	},
	[l.ma] = {
		[l.ale] = "󿧬",
		[l.ali] = "󿧬",
		[l.ike] = "󿴅",
		[l.kasi] = "󿧭",
		[l.ni] = "󿴂",
		[l.pona] = "󿴆",
		[l.tomo] = "󿧮",
	},
	[l.mama] = {
		[l.mama] = "󿧯",
		[l.meli] = "󿧰",
		[l.mije] = "󿧱",
		[l.tonsi] = "󿯒",
	},
	[l.meli] = {
		[l.ike] = "󿧲",
		[l.lili] = "󿧳",
		[l.mije] = "󿴇",
		[l.pona] = "󿧴",
		[l.sama] = "󿧵",
		[l.tonsi] = "󿯗",
		[l.unpa] = "󿧶",
		[l.wawa] = "󿯚",
	},
	[l.mije] = {
		[l.ike] = "󿧷",
		[l.lili] = "󿧸",
		[l.meli] = "󿴇",
		[l.pona] = "󿧹",
		[l.sama] = "󿧺",
		[l.tonsi] = "󿯠",
		[l.unpa] = "󿧻",
		[l.wawa] = "󿧼",
	},
	[l.musi] = {
		[l.lili] = "󿧽",
	},
	[l.mute] = {
		[l.mute] = "󿴝",
	},
	[l.nasin] = {
		[l.nanpa] = "󿯶",
		[l.sitelen] = "󿯸",
	},
	[l.nena] = {
		[l.kon] = "󿧾",
		[l.kute] = "󿧿",
		[l.lili] = "󿨀",
		[l.mama] = "󿨁",
		[l.meli] = "󿨂",
	},
	[l.nimi] = {
		[l.sin] = "󿶖",
	},
	[l.palisa] = {
		[l.lili] = "󿨃",
	},
	[l.pilin] = {
		[l.ala] = "󿨄",
		[l.ike] = "󿨅",
		[l.nasa] = "󿨆",
		[l.pakala] = "󿨇",
		[l.pona] = "󿨈",
		[l.sama] = "󿨉",
	},
	[l.pimeja] = {
		[l.jelo] = "󿴉",
		[l.laso] = "󿴊",
		[l.loje] = "󿴋",
	},
	[l.poki] = {
		[l.kon] = "󿨊",
		[l.len] = "󿨋",
		[l.lete] = "󿨌",
		[l.lili] = "󿨍",
		[l.seli] = "󿨎",
		[l.telo] = "󿨏",
		[l.tona] = "󿮯",
	},
	[l.pona] = {
		[l.ala] = "󿨐",
		[l.lili] = "󿨑",
		[l.lukin] = "󿨒",
		[l.mute] = "󿴞",
	},
	[l.selo] = {
		[l.len] = "󿨓",
		[l.soweli] = "󿨔",
	},
	[l.sike] = {
		[l.lili] = "󿨕",
	},
	[l.sitelen] = {
		[l.ike] = "󿨖",
		[l.ma] = "󿨗",
		[l.monsuta] = "󿨘",
		[l.pona] = "󿨙",
		[l.sitelen] = "󿨚",
		[l.tawa] = "󿨛",
		[l.toki] = "󿨜",
	},
	[l.sona] = {
		[l.ala] = "󿨝",
		[l.ike] = "󿨞",
		[l.lili] = "󿨟",
		[l.ma] = "󿨠",
		[l.nanpa] = "󿨡",
		[l.pona] = "󿨢",
		[l.sijelo] = "󿨣",
		[l.tenpo] = "󿨤",
		[l.toki] = "󿨥",
		[l.utala] = "󿨦",
	},
	[l.soweli] = {
		[l.kijetesantakalu] = "󿴩",
	},
	[l.supa] = {
		[l.lape] = "󿨧",
		[l.lawa] = "󿨨",
		[l.lupa] = "󿨩",
		[l.moku] = "󿨪",
		[l.monsi] = "󿨫",
		[l.pali] = "󿨬",
	},
	[l.telo] = {
		[l.lete] = "󿨭",
		[l.lili] = "󿨮",
		[l.sitelen] = "󿴌",
	},
	[l.tenpo] = {
		[l.ni] = "󿴃",
	},
	[l.toki] = {
		[l.ala] = "󿨯",
		[l.ike] = "󿨰",
		[l.pona] = "󿨱",
		[l.sin] = "󿨲",
		[l.sona] = "󿨳",
		[l.utala] = "󿨴",
	},
	[l.tomo] = {
		[l.lape] = "󿨵",
		[l.mani] = "󿨶",
		[l.moku] = "󿨷",
		[l.monsuta] = "󿨸",
		[l.nasin] = "󿨹",
		[l.ni] = "󿴄",
		[l.pali] = "󿨺",
		[l.sona] = "󿨻",
		[l.tawa] = "󿨼",
		[l.unpa] = "󿨽",
		[l.utala] = "󿨾",
	},
	[l.tonsi] = {
		[l.ike] = "󿯥",
		[l.lili] = "󿯦",
		[l.pona] = "󿯧",
		[l.sama] = "󿯨",
		[l.sin] = "󿯩",
		[l.unpa] = "󿯪",
		[l.wawa] = "󿯫",
	},
	[l.tu] = {
		[l.luka] = "󿩅",
		[l.tu] = "󿨿",
		[l.wan] = "󿩀",
	},
	[l.walo] = {
		[l.jelo] = "󿴍",
		[l.laso] = "󿴎",
		[l.loje] = "󿴏",
		[l.pimeja] = "󿯬",
	},
	[l.wan] = {
		[l.luka] = "󿩃",
		[l.tu] = "󿩁",
	},
	[l.wawa] = {
		[l.tenpo] = "󿯭",
	},
}
